# Generated by Django 5.1.3 on 2024-12-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_date', models.DateField(verbose_name='Puzzle Date')),
                ('puzzle_type', models.CharField(max_length=4)),
                ('puzzle_start', models.IntegerField()),
                ('puzzle_goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleDistinctSolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_sol', models.CharField(max_length=50)),
                ('found', models.BooleanField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.puzzles')),
            ],
        ),
    ]
