# Generated by Django 5.1.3 on 2024-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_rename_puzzles_puzzle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="puzzle_mode",
            field=models.CharField(default="standard", max_length=8),
            preserve_default=False,
        ),
    ]
